name: Pytest
on:
  pull_request:
  push:
    branches: [main,ci-dev]
jobs:
  conda-pytest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: install conda env with micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          cache-environment: false
      - name: install mesa with conda
        run: conda install -c conda-forge mesalib
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: pytest
        shell: bash -l {0}
        run: |
          export MUJOCO_GL=egl
          pytest test/